export const categories = [
  { value: 'AMM', label: 'AMM' },
  { value: 'Analytics', label: 'Analytics' },
  { value: 'App', label: 'App' },
  { value: 'Centralized Exchanges', label: 'Centralized Exchanges' },
  { value: 'Consumer', label: 'Consumer' },
  { value: 'Custodians', label: 'Custodians' },
  {
    value: 'DAOs and Network States',
    label: 'DAOs and Network States',
  },
  {
    value: 'Decentralized Exchange',
    label: 'Decentralized Exchange',
  },
  { value: 'DeFi', label: 'DeFi' },
  { value: 'Explorer', label: 'Explorer' },
  { value: 'Fiat On-ramp', label: 'Fiat On-ramp' },
  { value: 'Ecosystem Fund', label: 'Ecosystem Fund' },
  { value: 'Game', label: 'Game' },
  { value: 'Gaming', label: 'Gaming' },
  { value: 'Governance', label: 'Governance' },
  { value: 'Infrastructure', label: 'Infrastructure' },
  { value: 'Investment Fund', label: 'Investment Fund' },
  { value: 'Metaplex', label: 'Metaplex' },
  { value: 'Mobile', label: 'Mobile' },
  { value: 'News Sharing', label: 'News Sharing' },
  { value: 'NFT', label: 'NFT' },
  { value: 'Oracle', label: 'Oracle' },
  { value: 'Payments', label: 'Payments' },
  { value: 'Privacy', label: 'Privacy' },
  { value: 'Rpc', label: 'Rpc' },
  { value: 'SDK', label: 'SDK' },
  { value: 'Social Media', label: 'Social Media' },
  { value: 'SPL', label: 'SPL' },
  { value: 'Stablecoin', label: 'Stablecoin' },
  { value: 'Token', label: 'Token' },
  { value: 'Tools', label: 'Tools' },
  { value: 'Tools & Infrastructure', label: 'Tools & Infrastructure' },
  { value: 'Wallet', label: 'Wallet' },
];
