export const categories = [
  { value: 'amm', label: 'AMM' },
  { value: 'analytics', label: 'Analytics' },
  { value: 'cex', label: 'CEX' },
  { value: 'consumer', label: 'Consumer' },
  { value: 'custodians', label: 'Custodians' },
  { value: 'dao', label: 'DAO' },
  { value: 'defi', label: 'DeFi' },
  { value: 'dex', label: 'DEX' },
  { value: 'explorer', label: 'Explorer' },
  { value: 'fiat on-ramp', label: 'Fiat On-ramp' },
  { value: 'fund', label: 'Ecosystem Fund' },
  { value: 'gaming', label: 'Game' },
  { value: 'governance', label: 'Governance' },
  { value: 'investment fund', label: 'Investment Fund' },
  { value: 'metaplex', label: 'Metaplex' },
  { value: 'metaverse', label: 'Metaverse' },
  { value: 'mobile', label: 'Mobile' },
  { value: 'news sharing', label: 'News Sharing' },
  { value: 'nft', label: 'NFT' },
  { value: 'oracle', label: 'Oracle' },
  { value: 'payments', label: 'Payments' },
  { value: 'privacy', label: 'Privacy' },
  { value: 'rpc', label: 'RPC' },
  { value: 'sdk', label: 'SDK' },
  { value: 'social media', label: 'Social Media' },
  { value: 'spl', label: 'SPL' },
  { value: 'stablecoin', label: 'Stablecoin' },
  { value: 'token', label: 'Token' },
  { value: 'tools & infra', label: 'Tools & Infrastructure' },
  { value: 'wallet', label: 'Wallet' },
];
